inherit_from:
  - .rubocop_airbnb.yml

# Rails用に最適化
Rails:
  Enabled: true

# 文字数上限
LineLength:
  Max: 130

#rubocopで検証したくないフォルダを指定
AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/**/*'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - '**/Gemfile'
    - '**/spec/spec_helper.rb'
